import Container from '@/components/ui/Container';
import Wrapper from '@/components/ui/Wrapper';
import type { Metadata } from 'next';
import '../styles/globals.css';
import '../styles/nullstyle.css';

export const metadata: Metadata = {
  title: 'Floristry',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Wrapper>
          <Container>
            {/* header */}
            <div id="content">{children}</div>
            {/* footer */}
          </Container>
        </Wrapper>
      </body>
    </html>
  );
}
